### ISSUE TITLE
simstring not compiling on OSX

### ISSUE THREAD

**Issue by bevankoopman** [Georgetown-IR-Lab/QuickUMLS#1]
First, thanks for sharing this project.

I'm having trouble with the setup. Specifically, simstring does not compile on OS X (10.11.5). I've attached the trace of the errors.

Thanks.
[typescript.txt](https://github.com/Georgetown-IR-Lab/QuickUMLS/files/412532/typescript.txt)

**Comment by lucasoldaini** [comment]
Thanks for reporting this! Which version of the C++ compiler are you using?

**Comment by bevankoopman** [comment]
Here is the output of `g++ --version`:

`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

Thanks.

**Comment by bevankoopman** [comment]
I also tried installing the GCC 4.9 compiler (via homebrew) and then compiling simstring with that; however, it does not support the `-Wshorten-64-to-32` g++ flag which is stipulated when you run setup.py.in.

**Comment by lucasoldaini** [comment]
Someone else was having a similar issue with the original version of simstring; I've applied the same patch and created a pre-release version for you to test.

Can you please pull the repo again, and then run `bash setup_simstring.sh 3 v.1.1.2-prerelease` ? (change "3" to "2" if you'd like to install the Python 2 version)

(And yes, Docker instance should also work 😉)

**Comment by bevankoopman** [comment]
Thanks for your reply, @lucasoldaini.

Unfortunately, it is still failing (console log attached).
[terminal.txt](https://github.com/Georgetown-IR-Lab/QuickUMLS/files/419182/terminal.txt)

Sorry, I know this is a problem more with simstring than with QuickUMLS - would love to get it working though.

I might also look at producing a ubuntu based docker images with things on it. I'm not sure about licensing issues with UMLS though?

**Comment by lucasoldaini** [comment]
Unfortunately I don't have a OS X machine to test it on further.

If you decide to go with docker, you can use [minimal client-server library](https://github.com/lucasoldaini/QuickUMLS-client-server) I often use in my experiments. You'll have to tweak the settings in `start_server.sh`, but it should let you run QuickUMLS inside a server while the rest of your code runs on OS X.
