### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by jessika0991** [Georgetown-IR-Lab/QuickUMLS#16]
Hi all, 
I am annotating some string I have saved on a DB combining pyspark and QuickUMLS. However, I noticed from my output log that I frequently get this error:

> IO error: lock QuickUMLSMaster/QuickUMLS/cui-semtypes.db/cui.leveldb/LOCK: Resource temporarily unavailable

Do you have any idea why is this happening? I was not able to find any clue 
Thanks a lot

**Comment by soldni** [comment]
The lock for the `cui-semtypes` and `umls-simstring` is created when QuickUMLS object is created. Sometimes, if a script doesn't terminate successfully, the lock is not released when the QuickUMLS object is destroyed. In those cases, you can manually delete the lock.
