### ISSUE TITLE
SemTypes

### ISSUE THREAD

**Issue by aus10powell** [Georgetown-IR-Lab/QuickUMLS#17]
Hi,

First of all, great tool! Using it heavily right now. My group is looking into the semTypes and noticed in the constants.py those semTypes don't have as many as the UMLS (https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt). Wondering if there was a reason for this and should be updated?

**Comment by soldni** [comment]
Austin,

We intentionally limited the number of semantic types to those "that are typically associated with the four aspect of the medical decision criteria (namely symptoms, diagnostic tests, diagnoses, and 
treatments)" as suggested in [1]. In other words, we limited the semantic types to those typically associated with medical concepts in clinical literature. Feel free to modify the [constants.py](https://github.com/Georgetown-IR-Lab/QuickUMLS/blob/master/constants.py#L11) file to include all semantic types you need. 
 
----------------
[1] N. Limsopatham, C. Macdonald, and I. Ounis. [Inferring conceptual relationships to improve medical records search](https://pdfs.semanticscholar.org/1d22/fa7dc4467d83c0123c07a4d82387560629d7.pdf). OAIR, 2013.

**Comment by aus10powell** [comment]
@soldni 
That is what we were thinking and we did change the constants.py. In our case yes, the criteria you mentioned were at the majority of entities, but we couldn't ignore the minor cases

Thanks also for the reference.
