### ISSUE TITLE
LevelDBError: IO error: ../semtypes.leveldb/000063.ldb: Too many open files

### ISSUE THREAD

**Issue by magicliulei88** [Georgetown-IR-Lab/QuickUMLS#24]
I got following error message, and it always relate to 000063.ldb with error too many open files. Do you have any suggestions? 

LevelDBError                              Traceback (most recent call last)
<ipython-input-7-ee28ebc6101c> in <module>()
     20             Test2(path)
     21 
---> 22 Test2('/Users/magicliulei/Desktop/Ontology/QuickUMLS-master/folder_1')

<ipython-input-7-ee28ebc6101c> in Test2(rootDir)
     14         #matcher.match(text, best_match=True, ignore_syntax=False)
     15         #print(matcher.match(text, best_match=True, ignore_syntax=False))
---> 16         text_file.write(str(matcher.match(text, best_match=True, ignore_syntax=False)))
     17         text_file.close()
     18 

~/Desktop/Ontology/QuickUMLS-master/network.py in func_request(*args, **kwargs)
    158             # method_name
    159             if isinstance(data, Exception):
--> 160                 raise data
    161 
    162             return data

LevelDBError: IO error: Results/cui-semtypes.db/semtypes.leveldb/000063.ldb: Too many open files

**Comment by soldni** [comment]
@magicliulei88,

Please see [this issue](https://github.com/Georgetown-IR-Lab/QuickUMLS/issues/21) for a solution to your problem.

-Luca
