### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by aditya9211** [Georgetown-IR-Lab/QuickUMLS#28]
https://github.com/Georgetown-IR-Lab/QuickUMLS/blob/4a32fa8b59a1475082ceba9ea97c631247aa3c5a/toolbox.py#L80

Error occurs when using default Jaccard similarity and
when null word is sent (len(X) + len(Y) == intersec)

Please rectify it

**Comment by soldni** [comment]
Solved in the [latest release](https://github.com/Georgetown-IR-Lab/QuickUMLS/releases/tag/1.2.5).
