### ISSUE TITLE
Processing a whole document with QuickUMLS

### ISSUE THREAD

**Issue by bevankoopman** [Georgetown-IR-Lab/QuickUMLS#3]
What is the recommended method for processing a whole document with QuickUMLS?

I am currently reading in the whole document and passing to QuickUMLS? This is not very nice though. Is it best to process line by line?  Should you preprocess with sentence segmentation and then send to QuickUMLS (I thought it does sentence segmentation first anyway)?

I was going to implement a document processing script and create pull request to add to the repo.

Thanks.

**Comment by lucasoldaini** [comment]
I've only used it against whole documents. What is the issue with it? 

Feel free to make a PR for a document processing script :)
