### ISSUE TITLE
KeyError in constants.SPACY_LANGUAGE_MAP[self.language_flag]

### ISSUE THREAD

**Issue by tutubalinaev** [Georgetown-IR-Lab/QuickUMLS#30]
Hello,
thank you for the development of QuickUMLS! I have installed QuickUMLS with Russian UMLS concepts (-E RUS) and found the following issue:
Traceback (most recent call last):
  File "server.py", line 80, in <module>
    run_quickumls_server(opts)
  File "server.py", line 19, in run_quickumls_server
    verbose=opts.verbose
  File "/home/elena/umls/QuickUMLS/quickumls.py", line 91, in __init__
    spacy_lang = constants.SPACY_LANGUAGE_MAP[self.language_flag]
KeyError: 'RUS'

This is the obvious bug in constants.py since there is 'RUS' key in LANGUAGES which is not included in SPACY_LANGUAGE_MAP. 

Could you please fix it? Thank you in advance!

**Comment by soldni** [comment]
Thank you for the bug report! I just pushed a fix for this.
