### ISSUE TITLE
make_ngrams returns empty set when n > len(s)

### ISSUE THREAD

**Issue by vlsd** [Georgetown-IR-Lab/QuickUMLS#32]
https://github.com/Georgetown-IR-Lab/QuickUMLS/blob/8953b8739d7ad91bb7fea70d1346a0ebc2dfc1a2/toolbox.py#L70

This results in division by zero errors when calculating the similarity between two words that are shorter than n (even if the two words are identical!).

**Comment by soldni** [comment]
Thank you for noticing and the fix! Merged.
