### ISSUE TITLE
  Don't know how to compile leveldb for Windows!

### ISSUE THREAD

**Issue by shjb16** [Georgetown-IR-Lab/QuickUMLS#34]
I'm getting this error once i run the requirement.txt file on my windows machine.

**Comment by soldni** [comment]
Hi,

The installation of packages under `requirements.txt` happens **outside** QuickUMLS, so it is not related to this package itself. please contact the owner of the package that is not installing to get that solved. 

Best,
Luca

**Comment by SnowCat29** [comment]
Used [this solution](https://stackoverflow.com/questions/46901458/how-to-import-leveldb-in-python-3-5-on-windows) to overcome this problem.
