### ISSUE TITLE
Installation in Windows

### ISSUE THREAD

**Issue by SnowCat29** [Georgetown-IR-Lab/QuickUMLS#36]
Hi,

One of the requirements for the installation is leveldb, but it cannot be installed in Windows ("pip install leveldb"). Does that mean QuickUMLS cannot be installed in Windows? If it can, as suggested by Cygwin and Mingw support, could you please provide detailed installation instructions for Windows?

Thank you.

EDIT: Found a leveldb pyd file for Python 3.6 that allowed for the "import leveldb" command to work. The question now is the last part: Are you able to provide detailed instructions for installation on Windows?

**Comment by soldni** [comment]
Hi!

If you managed to get leveldb installed, the only thing you've left to do before running install.py is to get Simstring up and running. Can you try following the instructions from [here](https://github.com/Georgetown-IR-Lab/simstring) ?

Best,
Luca

**Comment by SnowCat29** [comment]
Thanks Luca,

I have followed the instructions that you referred to and with minor changes have installed Simstring and then instantiated QuickUMLS successfully.

The following changes were needed to get everything to work (python 3.6 with Anaconda):
- `python setup.py build_ext --inplace` (from setup_simstring.sh) would not use the Anaconda environment where libiconv was installed, and would fail not finding iconv.h. So had to use regular build and install for Simstring as per the link you provided:
```
python setup.py build
python setup.py install
```
That caused QuickUMLS installation to fail on line `from simstring import simstring` inside toolbox.py. Changing that to `import simstring` allowed the install to go through and subsequent use of the system.

Best regards,
Ivan

**Comment by soldni** [comment]
Great, thank you for letting me know!
