### ISSUE TITLE
Quickumls not working on Windows

### ISSUE THREAD

**Issue by shjb16** [Georgetown-IR-Lab/QuickUMLS#44]
Is QUICKUMLS compatible with window10?

**Comment by soldni** [comment]
It should! Please see instructions [here](https://github.com/Georgetown-IR-Lab/simstring) to get simstring running, then follow regular installation instructions.

**Comment by shjb16** [comment]
Thanks Luca, I'll try this.

**Comment by soldni** [comment]
Great! I've closed the issue for now, but feel free to re-open it if needed.
