### ISSUE TITLE
How to connect to the server from HTML/web applicaton

### ISSUE THREAD

**Issue by aganapa** [Georgetown-IR-Lab/QuickUMLS#46]
When quickumls is run in server mode, is it possible to communicate with the server from HTML/Web application (i.e., without using python on the client side). Is there any example source code that you can share. Appreciate it very much.

**Comment by soldni** [comment]
Hi @aganapa! If you look at the code in [`network.py`](https://github.com/Georgetown-IR-Lab/QuickUMLS/blob/master/quickumls/network.py) and [`server.py`](https://github.com/Georgetown-IR-Lab/QuickUMLS/blob/master/quickumls/server.py), you can see that the client and server communicate over port 4645 with buffer size of 4096. You could create a client in your language that connects to the sockets and sends/pulls the data in chunks. At the moment, data is pickled between the client and server, but we can switch to something like MessagePack if there is enough interest.
