### ISSUE TITLE
UMLS Installation

### ISSUE THREAD

**Issue by bwanglzu** [Georgetown-IR-Lab/QuickUMLS#5]
Where can i find the UMLS installation? I downloaded 2016AB-Full version from the official website, but it does not contains `MRCONSO.RRF` and `MRSTY.RRF`.

**Comment by lucasoldaini** [comment]
You can read about how extract MRCONSO.RRF and MRSTY.RRF on [chapter 8 of the UMLS book](https://www.ncbi.nlm.nih.gov/books/NBK9683/) or on the [help page of the MetamorphoSys tool](https://www.nlm.nih.gov/research/umls/implementation_resources/metamorphosys/index.html).
