### ISSUE TITLE
Getting definitions and synonyms for the resulting cui

### ISSUE THREAD

**Issue by vegetakarthhik** [Georgetown-IR-Lab/QuickUMLS#53]
Hi,
I am new to UMLS. We are working on healthcare related use case. UMLS has those short definitions for symptoms which will be very useful to augment out data and improve model performance. But I am able to get only cui from quickumls. Is there a way to extract the corresponding definitions and synonyms using quick umls pacakage?

**Comment by soldni** [comment]
Hi @vegetakarthhik,

Definitions are not included by design; I tried to keep the index as small as possible to improve memory efficiency. You can obtain definitions from the [MRDEF.RRF](https://www.ncbi.nlm.nih.gov/books/NBK9685/) file when using UMLS's Rich Release Format. 

Best,
Luca
