### ISSUE TITLE
repeated similarity calculations

### ISSUE THREAD

**Issue by bicycleman15** [Georgetown-IR-Lab/QuickUMLS#56]
https://github.com/Georgetown-IR-Lab/QuickUMLS/blob/bad4c50ae654ec4ea0bb021d6861b7370ff1ae9f/quickumls/core.py#L326
I feel the similarity calculation could be moved one `for` loop above to line `324`.

**Comment by soldni** [comment]
Hi @bicycleman15,

Thank you for letting me know -- I've just fixed it! This doesn't change execution time by much (calculating similarity is really fast, the bottleneck is retrieving candidates), so I'll push this out in the next release!

Best,
Luca
