### ISSUE TITLE
[BUG] error about "pip install quickumls"

### ISSUE THREAD

**Issue by JiangChao52** [Georgetown-IR-Lab/QuickUMLS#66]
**Describe the bug**
error about "pip install quickumls"

**To Reproduce**
When I attempt to install the QuickUMLS by using "pip install quickumls", it returns an error.

**Environment **
 - OS: win10
 - QuickUMLS version [1.4]
 - UMLS version [e.g. 2020AB]
 - python :3.7

**Additional context**
(onto) C:\Users\64863>pip install quickumls
Collecting quickumls
  Using cached quickumls-1.4.0.post1.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Users\64863\anaconda3\envs\onto\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\64863\\AppData\\Local\\Temp\\pip-install-jf5myo6n\\quickumls_76b1b226a8dd43daa9be15d99090c8ea\\setup.py'"'"'; __file__='"'"'C:\\Users\\64863\\AppData\\Local\\Temp\\pip-install-jf5myo6n\\quickumls_76b1b226a8dd43daa9be15d99090c8ea\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\64863\AppData\Local\Temp\pip-pip-egg-info-wcl6pbog'
         cwd: C:\Users\64863\AppData\Local\Temp\pip-install-jf5myo6n\quickumls_76b1b226a8dd43daa9be15d99090c8ea\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\64863\AppData\Local\Temp\pip-install-jf5myo6n\quickumls_76b1b226a8dd43daa9be15d99090c8ea\setup.py", line 74, in <module>
        setup_package()
      File "C:\Users\64863\AppData\Local\Temp\pip-install-jf5myo6n\quickumls_76b1b226a8dd43daa9be15d99090c8ea\setup.py", line 26, in setup_package
        readme = reader.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 2077: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by soldni** [comment]
hi @JiangChao52,

Windows support is not fully fleshed out; I try my best, but it is hard without a windows machine to test on. I would recommend installing QuickUMLS using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about). 

I am closing this issue for now, but feel free to reopen if that doesn't solve your issue. 

Best,
Luca
