### ISSUE TITLE
Problem installing quickumls on Windows

### ISSUE THREAD

**Issue by RonWilkinson** [Georgetown-IR-Lab/QuickUMLS#71]
In attempting to install quickumls on Windows10 and Python 3.8.5 in an Anaconda environment, I get the following log:

> (base) PS C:\Users\Ron> pip install quickumls
Collecting quickumls
  Downloading quickumls-1.4.0.post1.tar.gz (22 kB)
Requirement already satisfied: leveldb>=0.193 in c:\users\ron\anaconda3\lib\site-packages (from quickumls) (0.201)
Requirement already satisfied: numpy>=1.8.2 in c:\users\ron\anaconda3\lib\site-packages (from quickumls) (1.19.2)
Requirement already satisfied: spacy>=1.6.0 in c:\users\ron\anaconda3\lib\site-packages (from quickumls) (2.3.2)
Requirement already satisfied: unidecode>=0.4.19 in c:\users\ron\anaconda3\lib\site-packages (from quickumls) (1.2.0)
Requirement already satisfied: nltk>=3.3 in c:\users\ron\anaconda3\lib\site-packages (from quickumls) (3.5)
Collecting quickumls_simstring>=1.1.5r1
  Downloading quickumls_simstring-1.1.5r1.tar.gz (68 kB)
     |████████████████████████████████| 68 kB 1.2 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Ron\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ron\\AppData\\Local\\Temp\\pip-install-kzzwupen\\quickumls-simstring\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ron\\AppData\\Local\\Temp\\pip-install-kzzwupen\\quickumls-simstring\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Ron\AppData\Local\Temp\pip-pip-egg-info-ia24qkh_'
         cwd: C:\Users\Ron\AppData\Local\Temp\pip-install-kzzwupen\quickumls-simstring\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ron\AppData\Local\Temp\pip-install-kzzwupen\quickumls-simstring\setup.py", line 93, in <module>
        readme = reader.read()
      File "C:\Users\Ron\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 471: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by RonWilkinson** [comment]
I found instructions for successfully installing quickUMLS on Windows at the medspacy site.  I'm all set.

**Comment by burgersmoke** [comment]
I'm glad that our other documentation helped out.  If you have other issues, let me know since I've spent a lot of hours making sure that QuickUMLS can build in various environments.  Windows takes by far the most effort and care.
