### ISSUE TITLE
Installation error : simstring 

### ISSUE THREAD

**Issue by Gracelek** [Georgetown-IR-Lab/QuickUMLS#8]
the same issue with #1. Then, the issue #4 is tried and simstring is successfully installed.
But still, I got the TraceBack below.
> Traceback (most recent call last):
  File "/Users/gracelee/Downloads/QuickUMLS-1.2/toolbox.py", line 17, in <module>
    from simstring import simstring
ImportError: cannot import name 'simstring'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/users/gracelee/downloads/quickUMLS-1.2/install.py", line 12, in <module>
    from toolbox import countlines, CuiSemTypesDB, SimstringDBWriter, mkdir
  File "/Users/gracelee/Downloads/QuickUMLS-1.2/toolbox.py", line 19, in <module>
    from .simstring import simstring
ImportError: attempted relative import with no known parent package 

When I tried your suggestion in the issue #1, I have the error below.
>https://github.com/Georgetown-IR-Lab/simstring/archive/v.1.1.2-prerelease.tar.gz
'simstring' directory exists. If you proceed, the folder will be deleted. Continue? [y/n] y
Getting Simstring v.1.1.2-prerelease...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    138      0 --:--:--  0:00:01 --:--:--   138
100  119k  100  119k    0     0  45678      0  0:00:02  0:00:02 --:--:--  199k
Unpacking Simstring...
Making Simstring...
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory
Installing...
cp: simstring-v.1.1.2-prerelease/_*.so: No such file or directory
cp: simstring-v.1.1.2-prerelease/simstring.py: No such file or directory
Done!

**Comment by soldni** [comment]
Are you providing any release name when installing simstring? It looks like you're trying to use version 1.1.2-prerelease instead of 1.1.2. To fix that, simply run

```bash
PYTHON_VERSION=$(python -c 'import sys; print(sys.version_info[0])')
bash setup_simstring.py ${PYTHON_VERSION}
```

**Comment by Gracelek** [comment]
Simstring version was the problem. QuickUMLS is successfully installed. Thanks.
-G

**Comment by ElmoLee822** [comment]
I have the same error below.
How can I fix it?

> Traceback (most recent call last):
>   File "install.py", line 13, in <module>
>     from toolbox import countlines, CuiSemTypesDB, SimstringDBWriter, mkdir
>   File "/home/chihjung/QuickUMLS/toolbox.py", line 22, in <module>
>     from .simstring import simstring
> ValueError: Attempted relative import in non-package

Thanks.

**Comment by soldni** [comment]
Could you provide more info about which python version/OS are you attempting to install QuickUMLS on?

**Comment by ElmoLee822** [comment]
I use python3 to install on Ubuntu.
