### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by samlexrod** [Georgetown-IR-Lab/QuickUMLS#87]
I found that my UMLS installation failed with the exception `Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment`

We are using the following g++ version:
`g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`

**Environment **
 - OS: Unbuntu = 20.04.1
 - QuickUMLS version = 1.4
 - UMLS version =  2022AA

This might be the cause of my prior issue initializing quickumls.

---
Prior issue:
We are trying to initialize the system but we get the following error:
`terminate called after throwing an instance of 'cdbpp::builder_exception'
  what():  Inconsistent stream offset
Aborted (core dumped)`

It is throwing an error at 68.74%
 
We are using the following command:
`python -m quickumls.install <umls_installation_path> <destination_path> -d unqlite`

**Comment by samlexrod** [comment]
I have set the `export DISPLAY=:0.0` however, I get the `Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment` error still.

**Comment by soldni** [comment]
looking at this: QuickUMLS does not use any Java component; it's python + a C extension. 

Pretty sure the issues you are seeing are due to something outside QuickUMLS.
